micronaut:
  application:
    name: dcb
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: BEARER
    endpoints:
      login:
        enabled: true
    redirect:
      login-success: /secure/anonymous
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: http://localhost:8081/realms/dcb/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      grant-type: password
      client-id: micronaut
      client-secret: 4k8ScSZvLK1ExE6WTgMAPsqjcfitQDNj
      authorization:
        url: http://localhost:8081/realms/dcb/protocol/openid-connect/auth
      token:
        url: http://localhost:8081/realms/dcb/protocol/openid-connect/token
        auth-method: client-secret-post
#r2dbc:
#  datasources:
#    default:
#      url: r2dbc:postgresql://localhost:5432/postgres
#      username: "${db.username:placeholder}"
#      password: "${db.password:placeholder}"
#      schema-generate: CREATE_DROP
#      dialect: POSTGRES
#elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
netty:
  default:
    allocator:
      max-order: 3

